<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_menu_after_login</name>
   <tag></tag>
   <elementGuidId>c7250e1d-5dc7-426b-81a1-b0342b306ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;profile-menu&quot;]/div[3]/a[1]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;profile-menu&quot;]/div[3]/a[1]/li</value>
   </webElementProperties>
</WebElementEntity>
